# Titles to use for the report.
title: "RNA-Seq QC Reports"
subtitle: null
intro_text: "MultiQC reports for BRB-Seq Project."
report_header_info:
    - Job: '${LIBRARY_NAME}'

run_modules:
   - custom_content
   - star
   - featureCounts
   - fastqc 

# Fix for running two fastqc one with read2. Not sure 
extra_fn_clean_trim:
    - "_read2"
                        
# Pass fail checks on general statistics table
table_cond_formatting_rules:
    mqc-generalstats-fastqc_trimmed-percent_gc:
        pass:
            - gt: 35
            - lt: 70
        fail:
            - lt: 35
            - gt: 70
    mqc-generalstats-star-uniquely_mapped_percent:
        pass:
            - gt: 55
        warn:
            - lt: 55
        fail:
            - lt: 50
    mqc-generalstats-featurecounts-percent_assigned:
        pass:
            - gt: 55
        warn:
            - lt: 55
        fail:
            - lt: 50
    mqc-generalstats-fastqc_trimmed-avg_sequence_length:
        pass:
            - gt: 70
        fail: 
            - lt: 69

read_count_multiplier: 0.001
read_count_prefix: "K"
read_count_desc: "thousands"
base_count_multiplier: 0.001
base_count_prefix: "K"
base_count_desc: "thousands"


# Modules that should come at the top of the report
top_modules:
    - 'generalstats'
    - 'custom_content'
    - fastqc:
            name: "FastQC (raw)"
            anchor: "fastqc_raw"
            info: "This section reports FastQC results before adapter trimming."
            target: ""
            path_filters: 
                - "*_read2_fastqc.zip"
    - fastqc:
            name: "FastQC (trimmed)"
            anchor: "fastqc_trimmed"
            info: "This section reports FastQC results after adapter trimming."
            target: ""
            path_filters:
                - "*_read2_polyA_trimmed_fastqc.zip"
    - 'star'
    - 'featureCounts'

custom_plot_config:
  # Show the percentages tab by default for the FastQC sequence counts plot
  star_alignment_plot:
    cpswitch_c_active: False
  featureCounts_assignment_plot:
    cpswitch_c_active: False
  
table_columns_name:
  FastQC (raw):
    total_sequences: "Raw Reads (K)"
  FastQC (trimmed):
    total_sequences: "Trimmed (K)"
    avg_sequence_length: "Length (bp)"
    percent_duplicates: "% Dup"
  STAR:
    uniquely_mapped_percent: "% Mapped"
    uniquely_mapped: "Mapped (K)"
  featureCounts:
    Assigned: "Assigned (K)"

table_columns_placement:
  FastQC (raw):
    total_sequences: 920
  FastQC (trimmed):
    total_sequences: 940
    avg_sequence_length: 960
    percent_duplicates: 980
  STAR:
    uniquely_mapped: 1000
    uniquely_mapped_percent: 1020 
  featureCounts:
    Assigned: 1040
    percent_assigned: 1060  

# Remove the sequence counts section from fastqc
remove_sections:
    - fastqc_trimmed_fastqc_sequence_counts
    - fastqc_trimmed_fastqc_per_sequence_quality_scores
    - fastqc_trimmed_fastqc_per_base_n_content
    - fastqc_trimmed_fastqc_per_base_sequence_content
    - fastqc_trimmed_fastqc_overrepresented_sequences
    - fastqc_trimmed_fastqc_adapter_content
    - fastqc_trimmed_fastqc_sequence_duplication_levels
    - fastqc_trimmed_fastqc_status_checks
    - fastqc_raw_fastqc_per_base_sequence_quality
    - fastqc_raw_fastqc_per_sequence_quality_scores
    - fastqc_raw_fastqc_per_base_n_content
    - fastqc_raw_fastqc_per_sequence_gc_content
    - fastqc_raw_fastqc_per_base_sequence_content
    - fastqc_raw_fastqc_overrepresented_sequences
    - fastqc_raw_fastqc_adapter_content
    - fastqc_raw_fastqc_sequence_duplication_levels
    - fastqc_raw_fastqc_sequence_length_distribution
    - fastqc_raw_fastqc_status_checks

table_columns_visible:
  FastQC (trimmed):
    percent_duplicates: True
    avg_sequence_length: True
    percent_gc: False
  FastQC (raw):
    percent_duplicates: False
    percent_gc: False
  STAR:
    total_reads: True
    uniquely_mapped: True
  featureCounts:
    percent_assigned: False